# -*- coding: utf-8 -*-
"""Gratitude_day.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iVzI7fNSbCcGdppBaGRE2YY0FFMtN2ko
"""

from google.colab import drive
drive.mount('/content/drive')

"""# New Section"""

!pip install rawpy

import os
import cv2
import rawpy
from google.colab.patches import cv2_imshow
from tqdm import tqdm

i = 0
folder = '/content/img1/'

for filename in tqdm(os.listdir(folder)):

  
    try :

      image = rawpy.imread(os.path.join(folder,filename))
      img = image.postprocess()
      image = cv2.cvtColor(img,cv2.COLOR_RGB2BGR)
      v,h,_ = image.shape
    except:
      image = cv2.imread(os.path.join(folder,filename))
      v,h,_ = image.shape

    color = 255

    if v>=h:

        ver = 5000

        horiz = int((ver/v)*h)

        im2 = cv2.resize(image,dsize=(horiz,ver))


        crux = (5000-horiz)//2

        im2 = cv2.copyMakeBorder(im2,top=0,bottom=0,left=(5000-horiz)//2,right=(5000-horiz)//2, value=[color, color, color],borderType=cv2.BORDER_CONSTANT)

    else:

        horiz = 5000

        ver = int((horiz/h)*v)

        im2 = cv2.resize(image,dsize=(horiz,ver))


        crux = 200

        im2 = cv2.copyMakeBorder(im2,top=(5000-ver)//2,bottom=(5000-ver)//2,left=0,right=0, value=[color, color, color],borderType=cv2.BORDER_CONSTANT)
    fin = cv2.copyMakeBorder(im2,top=300,bottom=1500,left=300,right=300, value=[color, color, color],borderType=cv2.BORDER_CONSTANT)

    fin = cv2.rectangle(fin, (300, 5475), (5300, 6625), (244,244,244), -1)

    fin = cv2.putText(fin,":)", (500, 6175), cv2.FONT_HERSHEY_DUPLEX, 12, (0,0,0), 15)

    fin = cv2.copyMakeBorder(fin,top=45,bottom=45,left=45,right=45, value=[0, 0, 0],borderType=cv2.BORDER_CONSTANT)

    # cv2_imshow(cv2.resize(fin,dsize=(h//10, v//10)))
    cv2.imwrite(f'/content/drive/My Drive/Gratitude Day/img/image{i}.jpg', fin)

    i += 1;
    # break